#!/bin/sh

set -e

case "${1}" in
	install|upgrade)
		dpkg-divert --package live-tools --quiet --add --rename --divert /usr/bin/uptime.procps /usr/bin/uptime
		dpkg-divert --package live-tools --quiet --add --rename --divert /usr/share/man/man1/uptime.procps.1.gz /usr/share/man/man1/uptime.1.gz
		;;

	abort-upgrade)

		;;

	*)
		echo "preinst called with unknown argument \`$1'" >&2
		exit 1
		;;
esac

#DEBHELPER#

exit 0
