#!/bin/sh
set -e

if [ "$1" = "configure" ]
then
	# upgrade from live-tools >> 4.0.1
	if dpkg-divert --package live-tools --list | grep -F /usr/bin/uptime.orig.procps
	then
		dpkg-divert --package live-tools --quiet --remove --rename --divert /usr/bin/uptime.orig.procps /usr/bin/uptime
		dpkg-divert --package live-tools --quiet --remove --rename --divert /usr/share/man/man1/uptime.orig.procps.1.gz /usr/share/man/man1/uptime.1.gz
	fi
fi

#DEBHELPER#
