#!/bin/sh

## live-tools(7) - System Support Scripts
## Copyright (C) 2006-2012 Daniel Baumann <daniel@debian.org>
##
## live-tools comes with ABSOLUTELY NO WARRANTY; for details see COPYING.
## This is free software, and you are welcome to redistribute it
## under certain conditions; see COPYING for details.


set -e

_UPTIME="$(/usr/bin/uptime.procps)"

_DATE_HOST="$(date +%s)"

_DATE_LXC="$(stat /dev/pts | awk '/^Change: / { print $2, $3 }')"
_DATE_LXC="$(date +%s -d"${_DATE_LXC}")"

_UPTIME_LXC="$((${_DATE_HOST} - ${_DATE_LXC}))"

if [ "${_UPTIME_LXC}" -gt 172800 ]
then
	# LXC uptime >= 2 days
	_DAYS="$((${_UPTIME_LXC} / 86400))"

	_UPTIME="$(echo ${_UPTIME} | sed -e "s|up .* days,|up ${_DAYS} days,|")"
else
	# LXC uptime < 2 days
	_HOURS="$((${_UPTIME_LXC} / 3600))"
	_MINUTES="$((${_UPTIME_LXC} - ${_HOURS}))"
	_MINUTES="$((${_MINUTES} / 60))"

	_UPTIME="$(echo ${_UPTIME} | sed -e "s|up .*,  |up ${_HOURS}:${_MINUTES},  |")"
fi

echo " ${_UPTIME}"
